server:
  port: ":2045"
  name: "default"
  save_dir: "./download"
  work_max: 8
  dsn: "sqlite:./data.db"
  staticPath: "./resource/static"

log:
  path: "./log.log"
  level: "debug"
  logNu: "10"


groq:
  apiKey: ""
  cachePath: ""

translation:
  deeplX:
    url: ""
    apiKey: ""