server:
  listen: ":2045"
  name: "default"
  dsn: "sqlite:./data.db"
  staticPath: "./resource/static"

  downlaodMaxWorker: 1
  saveDir: ""
  cacheDir: ""
  httpClientProxy: http://127.0.0.1:7890


log:
  path: "./log/log.log"
  level: "debug"
  maxSize: 10 #  M
  maxAge: 30 # days


groq:
  apiKey: ""

translation:
  deeplX:
    url: ""
    apiKey: ""