server:
  listen: ":2045"
  name: "default"
  dsn: "sqlite:./data.db"
  staticPath: "./resource/static"

  downlaodMaxWorker: 1
  saveDir: "./download"
  cacheDir: "./download/cache"
  httpClientProxy: ""

log:
  path: "./log/log.log"
  level: "debug"
  maxSize: 10 #  M
  maxAge: 30 # days


groq:
  apiKey: ""

translation:
  deeplX:
    url: ""
    apiKey: ""


#subtitle:
#  watch: false
#  pattern: "(?i)\\.(mp4|avi|mkv|mov|wmv|flv|webm|rmvb|asf)$"
#  dirPath: ""
#  subtitleInput:
#    provider: "ggml-medium"
#    prompt: ""
#    temperature:
#    language: ""
#    translateTo: ""