name: Build Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
      # packages: write

    env:
      DOCKER_REGISTRY: "ghcr.io"
      DOCKER_USERNAME: ${{ github.repository_owner }}
      DOCKER_PASSWORD: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: make build_docker

      # - name: Build CUDA Docker image
      #   run: make build_docker_cuda

      - name: Push Docker image
        run: make  docker_push

      # - name: Push CUDA Docker image
      #   run: make docker_push_cuda
       
